uo_dict = {
    10010: ["SESI Alfenas José Barbosa da Costa"],
    10020: ["SESI Andradas Amadeu Tonon"],
    10030: ["SESI Araguari Escola José Alencar Gomes da Silva"],
    10040: ["SESI Araxá Professor Djalma Guimarães"],
    10100: ["SESI Barbacena Escola Oscar Magalhães Ferreira"],
    10101: ["SESI Barbacena Escola Oscar Magalhães Ferreira Unid II"],
    10110: ["SESI Belo Horizonte Escola Emília Massanti"],
    10120: ["SESI Belo Horizonte Escola General Onésimo Becker de Araújo"],
    10130: ["SESI Belo Horizonte Centro Cultural Sesiminas"],
    10150: ["SESI Belo Horizonte Escola Mariza Araújo"],
    10160: ["SESI Belo Horizonte Escola Hamleto Magnavacca"],
    10169: ["Centro Integrado SESI SENAI Complexo Horto"],
    10170: ["SESI Belo Horizonte Escola Newton Antônio da Silva Pereira"],
    10190: ["SESI Betim Clube do Trabalhador Francisco Netto Motta"],
    10195: ["SESI Betim Escola Maria Madalena Nogueira"],
    10250: ["SESI Cataguases Rodrigo Lanna"],
    10271: ["SESI Uberlândia Unidade de Segurança e Saúde no Trabalho"],
    10272: ["SESI Montes Claros Unidade de Segurança e Saúde no Trabalho"],
    10273: ["SESI Escola Montes Claros"],
    10300: ["SESI Contagem Centro de Educação Infantil Leonor Franco"],
    10310: ["SESI Belo Horizonte Unidade de Segurança e Saúde no Trabalho"],
    10311: ["SESI Betim Unidade de Segurança e Saúde no Trabalho"],
    10312: ["SESI São João Batista"],
    10320: ["SESI Contagem Escola Alvimar Carneiro de Rezende"],
    10330: ["SESI Contagem Escola Benjamin Guimarães"],
    10340: ["SESI Contagem Restaurante do Trabalhador Henriqueta Maria Prieto"],
    10345: ["SESI Belo Horizonte Museu de Artes e Ofícios"],
    10434: ["Centro de Inovação em Ergonomia"],
    10455: ["SESI Conceição do Mato Dentro Unidade de Segurança e Saúde no Trabalho"],
    10460: ["SESI Curvelo Arthur Brito Bezerra Mello"],
    10490: ["SESI Divinópolis Escola Cel. Jovelino Rabelo"],
    10492: ["SESI Divinópolis Unidade de Segurança e Saúde no Trabalho"],
    10495: ["SENAI Belo Horizonte Centro de Treinamento da Tecnologia da Informação"],
    10880: ["SESI Governador Valadares Abílio Rodrigues Patto"],
    10881: ["SESI Governador Valadares Unidade de Segurança e Saúde no Trabalho"],
    10930: ["SESI Ipatinga Escola Rinaldo Campos Soares"],
    10940: ["SESI Ipatinga Escola Santa Rita de Cássia"],
    10941: ["SESI Ipatinga Unidade de Segurança e Saúde no Trabalho"],
    10970: ["SESI Itajubá Vitor Vieira dos Santos"],
    10971: ["SESI Itajubá Escola Aureliano Chaves"],
    10980: ["SESI Itaúna Escola Dário Gonçalves de Souza"],
    10990: ["SESI Ituiutaba Escola Dolores Peres Gomes da Silva"],
    11000: ["SESI João Monlevade Dr. Schlacher"],
    11010: ["SESI Juiz de Fora Unidade de Segurança e Saúde no Trabalho"],
    11020: ["SESI Juiz de Fora UI"],
    11021: ["SENAI Juiz de Fora UI Luiz Adelar Scheuer"],
    11030: ["SESI Juiz de Fora Clube Campestre Nansen Araújo"],
    11040: ["SESI Juiz de Fora Centro Esportivo do Trabalhador José Weiss"],
    11045: ["SESI Juiz de Fora Escola Granbery"],
    11130: ["SESI Montes Claros Clube do Trabalhador Valdemar Versiani dos Anjos"],
    11280: ["SESI Ouro Branco Unidade de Saude e Segurança do Trabalho"],
    11295: ["SESI Pará de Minas Escola Dr. Celso Charuri"],
    11300: ["SESI Paracatu Aurora Avelino de Macedo"],
    11330: ["SESI Patos de Minas Pedro Pereira Santos"],
    11340: ["SESI Pedro Leopoldo Escola Maria José d’Almeida Mello"],
    11360: ["SESI Pirapora Sebastião Augusto de Lima"],
    11740: ["SESI Ponte Nova Gastão Ferreira Santos"],
    11770: ["SESI Pouso Alegre Irmão Gino Maria Rossi"],
    11775: ["SESI Pouso Alegre Escola Orlando Chiarini"],
    11880: ["SESI Uberaba Centro Cultural José Maria Barra"],
    11970: ["SESI Santa Luzia Escola João Carlos Giovannini"],
    11979: ["SESI São Gonçalo do Sapucaí Escola José Bento Nogueira Junqueira"],
    11980: ["SESI São João del Rei Escola Dom Bosco"],
    11981: ["SESI São João Nepomuceno Escola Robson Braga de Andrade"],
    12061: ["SESI Sete Lagoas Escola Otoni Alves Costa"],
    12068: ["SESI Belo Horizonte Escola Coração Eucarístico"],
    12170: ["SESI Escola Três Corações"],
    12180: ["SESI Três Pontas Professor Josino de Brito Campos"],
    12200: ["SESI Ubá Escola José Alencar Gomes da Silva"],
    12210: ["SESI Uberaba Escola Alberto Martins Fontoura Borges"],
    12211: ["SESI Uberaba Escola Alberto Martins Fontoura Borges Unidade II"],
    12215: ["SESI Uberaba Unidade de Segurança e Saúde no Trabalho"],
    12220: ["SESI Uberaba Clube José Alencar Gomes da Silva"],
    12230: ["SESI Uberlândia Escola Guiomar de Freitas Costa"],
    12250: ["SESI Uberlândia Virgílio Galassi"],
    12602: ["Programa Escola Móvel SESI"],
    12610: ["SESI Varginha Hylio Foresti"],
    12611: ["SESI Varginha Escola Aloysio Ribeiro de Almeida"],
    12613: ["SESI Varginha Escola Aloysio Ribeiro de Almeida Unidade II"],
    12620: ["SESI Vespasiano Escola Antônio Quirino da Costa"],
    12650: ["SENAI Araguari UI Mário Abdalla"],
    12660: ["SENAI Araxá UI Djalma Guimarães"],
    12670: ["SENAI Arcos CFP Eliezer Vitorino Costa"],
    12675: ["SENAI Barão de Cocais CFP Guilherme Caldas Emrich"],
    12680: ["SENAI Barbacena CFP Olavo Machado"],
    12700: ["SENAI Belo Horizonte Horto"],
    12720: [
        "LACC - LABORATÓRIO DE CALIBRAÇÃO DO CETEL ELETRICIDADE",
        "LAE - LABORATÓRIO DE ACIONAMENTOS ELETRÔNICOS",
    ],
    12721: ["INSTITUTO SENAI DE TECNOLOGIA QUÍMICA"],
    12722: ["INSTITUTO SENAI DE TECNOLOGIA EM MEIO AMBIENTE"],
    12723: ["INSTITUTO SENAI DE TECNOLOGIA EM ALIMENTOS E BEBIDAS"],
    12724: ["INSTITUTO SENAI DE TECNOLOGIA AUTOMOTIVA"],
    12725: ["Centro de Inovação e Tecnologia SENAI FIEMG"],
    12726: ["GERÊNCIA DE METROLOGIA"],
    12729: ["INSTITUTO SENAI DE INOVAÇÃO EM PROCESSAMENTO MINERAL"],
    12730: ["SENAI Belo Horizonte CFP Américo Renê Giannetti"],
    12735: ["INSTITUTO SENAI DE INOVAÇÃO EM ENGENHARIA DE SUPERFÍCIES"],
    12736: ["INSTITUTO SENAI DE TECNOLOGIA EM METALMECÂNICA"],
    12740: [
        "SENAI Belo Horizonte CFP Paulo de Tarso",
        "LABORATÓRIO DE ENSAIOS EM SISTEMAS E MATERIAL DE CONSTRUÇÃO",
    ],
    12750: ["LABORATÓRIO DE ENSAIOS E PESQUISAS DE QUÍMICA TÊXTIL"],
    12800: ["SENAI Betim CETEM Maria Madalena Nogueira"],
    12884: ["SENAI Belo Horizonte CFP Nansen Araujo"],
    12910: ["SENAI Cataguases CFP José Ignácio Peixoto"],
    12921: [
        "SENAI Cláudio CFP Risoleta Tolentino Neves",
        "LABORATÓRIO DE ENSAIOS E ANÁLISES METALOGRÁFICAS-LAEMF",
    ],
    12925: ["SENAI Conceição do Mato Dentro CFP José Aparecido de Oliveira"],
    12959: ["SENAI Contagem CEDETEM Petronio Machado Zica"],
    12960: ["SENAI Contagem CFP Alvimar Carneiro Rezende"],
    12970: ["SENAI Contagem CFP Euvaldo Lodi"],
    12971: ["SENAI Centro de Treinamento e Desenvolvimento da Indústria 4.0"],
    12982: ["SENAI Contagem UI Nenem Scariolli"],
    13030: ["SENAI Divinópolis CFP Anielo Greco"],
    13040: ["SENAI Extrema CFP Janez Hlebanja"],
    13041: ["SESI Escola Extrema"],
    13050: ["SENAI Formiga CT Luiz Rodrigues da Costa"],
    13070: ["TECNOLOGIAS PARA O EMPREENDEDOR"],
    13090: ["SENAI Governador Valadares UI Luiz Chaves"],
    13093: [
        "SENAI Ipatinga UI Rinaldo Campos Soares",
        "LABORATÓRIO DE ENSAIOS MECÂNICOS E ANÁLISES DE AGREGADO SIDERÚRGICO - LEMAAS",
    ],
    13100: ["SENAI Itabira CFP Pedro Martins Guerra"],
    13106: ["SENAI Itabirito CFP Laércio Garcia Nogueira"],
    13110: ["SENAI Itajubá CFP Aureliano Chaves"],
    13120: [
        "SENAI Itaúna CETEF Marcelino Corradi",
        "Laboratório de Ensaios e Análises em Materiais – LAMAT",
    ],
    13121: ["SESI Itaúna Unidade de Segurança e Saúde no Trabalho"],
    13130: ["SENAI Ituiutaba UI Bebé Martins"],
    13140: ["SENAI João Monlevade UI Nansen Araújo"],
    13150: ["SENAI Juiz de Fora CFP José Fagundes Netto"],
    13172: ["SENAI Mariana CFP Dr. José Luciano Duarte Penido"],
    13180: ["SENAI Montes Claros CFP Luiz de Paula"],
    13190: ["SENAI Muriaé CFP Cézar Augusto Bianchi Botaro"],
    13200: ["SENAI Nova Lima CFP Afonso Greco"],
    13210: [
        "SENAI Nova Serrana CFP Geny José Ferreira",
        "LABORATÓRIO DE ENSAIOS FÍSICOS EM CALÇADOS",
    ],
    13230: ["SENAI Pará de Minas UI Dr. Celso Charurí"],
    13232: ["SENAI Ouro Branco CFP"],
    13240: ["SENAI Paracatu UI Epitácio Cardoso Naves"],
    13250: ["SENAI Patos de Minas UI Anávio Braz de Queiroz"],
    13261: ["SENAI Pirapora UI Pirapora"],
    13270: ["SENAI Pedro Leopoldo UI Gerson Dias"],
    13275: ["SENAI Pirapetinga CFP Dirceu de Oliveira Martins"],
    13290: ["SENAI Poços de Caldas CFP João Moreira Salles"],
    13300: ["SENAI Ponte Nova CFP São Vicente de Paulo"],
    13310: ["SENAI Pouso Alegre CFP Orlando Chiarini"],
    13365: ["SENAI São Sebastião do Paraíso CFP Monsenhor Jerônimo Mancini"],
    13370: ["SENAI Santa Luzia UI João Carlos Giovannini"],
    13371: [
        "SENAI Santa Rita do Sapucaí UI CDTSVE Stefan Bogdan Salej",
        "LABORATÓRIO DE PROTOTIPAGEM MECÂNICA E DESIGN",
    ],
    13380: [
        "SENAI Santo Antônio do Monte CTP Oscar José do Nascimento",
        "LABORATÓRIO DE QUALIDADE EM PIROTÉCNICOS E MEIO AMBIENTE",
    ],
    13382: ["SENAI São Gonçalo do Pará CT Luiz Nogueira da Silva"],
    13383: ["SENAI São Gonçalo do Rio Abaixo CFP José Fernando Coura"],
    13385: ["SENAI São Gonçalo do Sapucaí UI José Bento Nogueira Junqueira"],
    13390: ["SENAI São João Del Rei UI Sílvio Assunção Teixeira"],
    13400: ["SENAI São João Nepomuceno UI Robson Braga de Andrade"],
    13451: ["SENAI Sete Lagoas Fundação Zerrener"],
    13463: ["SENAI Timóteo CFP Luciano José de Araújo"],
    13470: ["SENAI Três Marias CFP Ademar Marra"],
    13485: ["SENAI Turmalina CFP"],
    13490: [
        "SENAI Ubá UI José Alencar Gomes da Silva",
        "LABORATÓRIO DE ENSAIOS EM MADEIRAS, MÓVEIS E TINTAS",
    ],
    13500: ["SENAI Uberaba CFP Fidelis Reis"],
    13510: [
        "SENAI Uberlândia CETAL Fábio de Araújo Motta",
        "LABORATÓRIO DE ENSAIOS EM ALIMENTOS E MEIO AMBIENTE",
        "LABORATÓRIO DE ENSAIOS EM MATERIAIS DA CONSTRUÇÃO CIVIL",
    ],
    13520: ["SENAI Uberlândia CFP Fábio de Araújo Motta"],
    13523: ["SENAI Uberlândia CFP Dr. Celso Charuri"],
    13527: [
        "SENAI Belo Horizonte Unidade de Escolas Móveis",
        "Unidade Móvel - Automação",
        "Unidade Móvel - Costura Industrial",
        "Unidade Móvel - Construção Civil",
        "Unidade Móvel - Couro e Calçados",
        "Unidade Móvel - Instrumentação e Controle de Processos Industriais",
        "Unidade Móvel - Manutenção Eletrica Industrial",
        "Unidade Móvel - Manutenção Mecânica Industrial",
        "Unidade Móvel - Panificação e Confeitaria",
        "Unidade Móvel - Simulação de Máquinas Pesadas",
        "Unidade Móvel - Soldagem",
        "Unidade Móvel - Usinagem CNC",
    ],
    13615: ["SENAI Vazante CFP Marcelo Ianhez"],
    13620: ["SENAI Varginha UI Aloysio Ribeiro de Almeida"],
    13630: ["SENAI Várzea da Palma CFP Joaquim de Paula Ferreira"],
    13632: ["SENAI Vespasiano UI Luiz César Albertini"],
    13635: ["SENAI Visconde do Rio Branco CFP Silvio Benatti"],
    13637: ["SENAI Lagoa Santa LABFAB"],
    11740: ["SESI Ponte Nova Gastão Ferreira Santos"],
    11770: ["SESI Pouso Alegre Irmão Gino Maria Rossi"],
    11775: ["SESI Pouso Alegre Escola Orlando Chiarini"],
    11979: ["SESI São Gonçalo do Sapucaí Escola José Bento Nogueira Junqueira"],
    11980: ["SESI São João del Rei Escola Dom Bosco"],
    11981: ["SESI São João Nepomuceno Escola Robson Braga de Andrade"],
    12230: ["SESI Uberlândia Escola Guiomar de Freitas Costa"],
    12250: ["SESI Uberlândia Virgílio Galassi"],
    13093: [
        "SENAI Ipatinga UI Rinaldo Campos Soares",
        "LABORATÓRIO DE ENSAIOS MECÂNICOS E ANÁLISES DE AGREGADO SIDERÚRGICO - LEMAAS",
    ],
    13121: ["SESI Itaúna Unidade de Segurança e Saúde no Trabalho"],
}